-- دربافت فعالیت کاربران

-- SELECT
--     A_ID, SENDER_ID, CONTEXT, SEND_DATE
-- FROM
--     USERS
--     INNER JOIN BLOCKED_USERS ON USERS.U_ID = BLOCKED_USERS.BLOCKER
--     INNER JOIN AVA ON USERS.U_ID = AVA.SENDER_ID
--     INNER JOIN (
--         SELECT
--             U_ID,
--             USER_NAME AS BLOCKED_USERNAME
--         FROM
--             USERS
--     ) U ON BLOCKED = U.U_ID
-- WHERE
--     USER_NAME = %(target_username)s -- TARGET
--     AND BLOCKED_USERNAME <> %(request_from_username)s
--     AND COMMENT_TO_AVA_ID IS NULL;

SELECT
    A_ID, SENDER_ID, CONTEXT, SEND_DATE
FROM
    USERS
    INNER JOIN BLOCKED_USERS ON USERS.U_ID = BLOCKED_USERS.BLOCKER
    INNER JOIN AVA ON USERS.U_ID = AVA.SENDER_ID
    INNER JOIN (
        SELECT
            U_ID,
            USER_NAME AS BLOCKED_USERNAME
        FROM
            USERS
    ) U ON BLOCKED = U.U_ID
WHERE
    USER_NAME = "BBbB"                      -- TARGET USERNAME
    AND BLOCKED_USERNAME <> "U1_USERNAME"  -- REQUEST FROM USERNAME
    AND COMMENT_TO_AVA_ID IS NULL;


SELECT
    A_ID, SENDER_ID, CONTEXT, SEND_DATE
FROM
    USERS
    INNER JOIN BLOCKED_USERS ON USERS.U_ID = BLOCKED_USERS.BLOCKER
    INNER JOIN AVA ON USERS.U_ID = AVA.SENDER_ID
    INNER JOIN (
        SELECT
            U_ID,
            USER_NAME AS BLOCKED_USERNAME
        FROM
            USERS
    ) U ON BLOCKED = U.U_ID
WHERE
    USER_NAME = "BBbB"                      -- TARGET USERNAME
    AND BLOCKED_USERNAME <> "aaAA"  -- REQUEST FROM USERNAME
    AND COMMENT_TO_AVA_ID IS NULL;


SELECT
    A_ID, SENDER_ID, CONTEXT, SEND_DATE
FROM
    USERS
    INNER JOIN BLOCKED_USERS ON USERS.U_ID = BLOCKED_USERS.BLOCKER
    INNER JOIN AVA ON USERS.U_ID = AVA.SENDER_ID
    INNER JOIN (
        SELECT
            U_ID,
            USER_NAME AS BLOCKED_USERNAME
        FROM
            USERS
    ) U ON BLOCKED = U.U_ID
WHERE
    USER_NAME = "aaAA"                      -- TARGET USERNAME
    AND BLOCKED_USERNAME <> "t"  -- REQUEST FROM USERNAME
    AND COMMENT_TO_AVA_ID IS NULL;




