-- INSERT IGNORE INTO
--     FOLLOWS (FOLLOWER, FOLLOWED)
-- SELECT
--     U1.U_ID,
--     U2.U_ID
-- FROM
--     USERS AS U1
--     CROSS JOIN USERS AS U2
-- WHERE
--     U1.USER_NAME = %(follower)s
--     AND U2.USER_NAME = %(followed)s;



INSERT
    IGNORE INTO FOLLOWS (FOLLOWER, FOLLOWED)
SELECT
    U1.U_ID,
    U2.U_ID
FROM
    USERS AS U1
    CROSS JOIN USERS AS U2
WHERE
    U1.USER_NAME = "U1_USERNAME"
    AND U2.USER_NAME = "aaAA";

INSERT IGNORE INTO
    FOLLOWS (FOLLOWER, FOLLOWED)
SELECT
    U1.U_ID,
    U2.U_ID
FROM
    USERS AS U1
    CROSS JOIN USERS AS U2
WHERE
    U1.USER_NAME = "U1_USERNAME"
    AND U2.USER_NAME = "BBbB";

INSERT IGNORE INTO
    FOLLOWS (FOLLOWER, FOLLOWED)
SELECT
    U1.U_ID,
    U2.U_ID
FROM
    USERS AS U1
    CROSS JOIN USERS AS U2
WHERE
    U1.USER_NAME = "BBbB"
    AND U2.USER_NAME = "aaAA";

INSERT IGNORE INTO
    FOLLOWS (FOLLOWER, FOLLOWED)
SELECT
    U1.U_ID,
    U2.U_ID
FROM
    USERS AS U1
    CROSS JOIN USERS AS U2
WHERE
    U1.USER_NAME = "BBbB"
    AND U2.USER_NAME = "U1_USERNAME";

INSERT IGNORE INTO
    FOLLOWS (FOLLOWER, FOLLOWED)
SELECT
    U1.U_ID,
    U2.U_ID
FROM
    USERS AS U1
    CROSS JOIN USERS AS U2
WHERE
    U1.USER_NAME = "U44"
    AND U2.USER_NAME = "U1_USERNAME";

INSERT IGNORE INTO
    FOLLOWS (FOLLOWER, FOLLOWED)
SELECT
    U1.U_ID,
    U2.U_ID
FROM
    USERS AS U1
    CROSS JOIN USERS AS U2
WHERE
    U1.USER_NAME = "BBbB"
    AND U2.USER_NAME = "U44";

