CREATE TABLE LIKES (
    USER_ID     BIGINT UNSIGNED NOT NULL,
    AVA_ID      BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (USER_ID, AVA_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(U_ID) ON UPDATE CASCADE,
    FOREIGN KEY (AVA_ID) REFERENCES AVA(A_ID) ON UPDATE CASCADE
);