CREATE TABLE CREATE_LOGS (
    USER_ID            BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    USER_NAME          VARCHAR(20) NOT NULL,
    CREATE_DATE        DATETIME DEFAULT NOW(),

    FOREIGN KEY (USER_ID) REFERENCES USERS(U_ID) ON UPDATE CASCADE

);  