
CREATE TABLE AVA_SPECS (
    AVA_ID  BIGINT UNSIGNED NOT NULL,
    SPEC_ID BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY  (AVA_ID, SPEC_ID),
    FOREIGN KEY  (AVA_ID) REFERENCES AVA(A_ID) ON UPDATE CASCADE,
    FOREIGN KEY  (SPEC_ID) REFERENCES SPECS(S_ID) ON UPDATE CASCADE

);


