CREATE TABLE MSG (
    M_ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SENDER_ID BIGINT UNSIGNED NOT NULL,
    RECEIVER_ID BIGINT UNSIGNED NOT NULL,
    CONTEXT VARCHAR(256) DEFAULT NULL,
    AVA_ID BIGINT UNSIGNED DEFAULT NULL,
    MSG_DATE DATETIME DEFAULT NOW(),
    FOREIGN KEY (AVA_ID) REFERENCES AVA(A_ID), -- ON UPDATE CASCADE,
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(U_ID) ON UPDATE CASCADE,
    FOREIGN KEY (RECEIVER_ID) REFERENCES USERS(U_ID) ON UPDATE CASCADE,
    CHECK (
        CONTEXT IS NOT NULL
        OR AVA_ID IS NOT NULL
    )
);