CREATE TABLE AVA_LOGS (
    A_ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SENDER_ID BIGINT UNSIGNED NOT NULL,
    SEND_DATE DATETIME NOT NULL DEFAULT NOW(),

    FOREIGN KEY (A_ID) REFERENCES AVA(A_ID) ON UPDATE CASCADE,
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(U_ID) ON UPDATE CASCADE
);