CREATE TABLE AVA (
    A_ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SENDER_ID BIGINT UNSIGNED NOT NULL,
    CONTEXT VARCHAR(256) NOT NULL,
    SEND_DATE DATETIME NOT NULL DEFAULT NOW(),
    COMMENT_TO_AVA_ID BIGINT UNSIGNED DEFAULT NULL,
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(U_ID) ON UPDATE CASCADE,
    FOREIGN KEY (COMMENT_TO_AVA_ID) REFERENCES AVA(A_ID) ON UPDATE CASCADE
);