CREATE TABLE SPECS (
    S_ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    S_TEXT VARCHAR(6) NOT NULL UNIQUE,
    CHECK (
        S_TEXT REGEXP '^[#][a-zA-Z][a-zA-Z][a-zA-Z][a-zA-Z][a-zA-Z]$'
    )
);